// This file gets generated by Astro automatically. It deals with types for TypeScript purposes.
/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

declare namespace App {
    interface Locals extends Runtime {
        otherLocals: {
            test: string;
        };
    }
}
