// This file gets generated by Astro automatically. It deals with types for TypeScript purposes.
/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

interface Env {
    TURNSTILE_SECRET_KEY: string;
    GMAIL_USER: string;
    GMAIL_APP_PASSWORD: string;
}

type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

declare namespace App {
    interface Locals extends Runtime {
        otherLocals: {
            test: string;
        };
    }
}
